on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    # - name: Azure Policy Compliance Scan
    #   uses: Azure/policy-compliance-scan@v0
    #   with:
    #     # Mandatory. Takes full identifier for one or more azure resources, resource groups or subscriptions. The on-demand policy compliance scan is triggered for all of these. 
    #     # The ID can generally be found in the properties section of the resource in Azure Portal.
    #     scopes: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION }}
        
      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters: 'storagePrefix=greg storageSKU=Standard_LRS'
        failOnStdErr: false
